name: Validations

on:
  pull_request:

jobs:
  validate-generation:
    # This job ensures that developers don't add Jsonnet files and forget to generate matching JSON files
    name: Validate all Jsonnet files have generated JSON files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install NPM dependencies
        run: npm ci

      - name: Validate generated JSON files
        run: npm run validateGeneration

  run-tests:
    name: Runs all Jest tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install NPM dependencies
        run: npm ci

      - name: Run tests
        run: npm test
